import os
import joblib
from pymongo import MongoClient
from pydantic import BaseModel,FilePath
from pathlib import Path
from typing import List
from fastapi import FastAPI, status
import random
import uvicorn
import pandas as pd
import sqlite3
import shutil
import cv2
from pathlib import Path
from rich.console import Console
from rich.table import Table
from pdf2image import convert_from_path, convert_from_bytes
from utils import encode
from pqdm.threads import pqdm

app = FastAPI()

conn = sqlite3.connect(database="W9_logs.sqlite")



class verify_inp(BaseModel):
    picture: str

class output_model(BaseModel):

      """Used to validate the datatypes and structures to ensure data-integrity

      fpath will be used to store the input file path
      b64_imgs will save the input images as a list of b64 strings
      scores will save list of scores
      bboxes will store a list of lists containing bboxes coordinates
      classes will store a list of integers corresponding to classes indices
      w9_images will save list of string paths corresponding to W9 images
      other_images will save a list of string paths corresponding to other images
      """

      fpath : str
      b64_imgs : List[str]
      scores : List[List[float]]
      bboxes : List[List[List[float]]]
      classes : List[List[int]]
      w9_images : List[str]
      other_images : List[str]
      detections : List[int]



@app.get('/status')
async def status_(status_code=status.HTTP_200_OK):
      return {
      "status" : f"ALIVE"
      }


@app.post('/insert/{fpath:path}', response_model=output_model, status_code=status.HTTP_201_CREATED)
async def insert_to_db(fpath : str):
    assert type(fpath) == str , "path of file should be of string type"
    pth = Path(fpath)
    suff = pth.suffix
    if suff == ".tiff":
        ret, images = cv2.imreadmulti(Path(fpath).as_posix(), [], cv2.IMREAD_ANYCOLOR)



        print(f"{len(images)} images are found ... ")
        tab = Table(title="images shapes", title_style = "bold yellow on black",style="cyan")
        tab.add_column("shapes", style="green", justify="center")

        # %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
        #                      debug the input images
        # %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
        if os.path.exists("images_from_tiff_pdf"):
            shutil.rmtree("images_from_tiff_pdf")
        Path("images_from_tiff_pdf").mkdir(parents=True, exist_ok=True)

        for idx, i in enumerate(images):
            tab.add_row(f"{i.shape}")
            cv2.imwrite(f"images_from_tiff_pdf/{idx}.jpg", i)
            # cv2.imshow("frame", i)
            # k = cv2.waitKey() & 0xFF
            # if k == ord('q'):
            #     cv2.destroyAllWindows()
        

        Console().print(tab)

        # %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
        #                      conver to base64
        # %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

        images = list(Path("images_from_tiff_pdf").glob("*.jpg"))
        images_ = [{"picture":k.as_posix()} for k in images]
        images_ = [verify_inp(**i) for i in images_]
        encoded_strings = pqdm(images_, encode, n_jobs=4)

        # %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
        #                      do inference - single batch
        # %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
        if os.path.exists("detections"): # if dir. already exists delete it
            shutil.rmtree("detections")
        Path("detections").mkdir(exist_ok=True, parents=True) # make a new dir for this experiment
        string_ = "   ".join([j.as_posix() for j in images])
        
        os.system(f"python demo/w9_predict.py  --config-file configs/custom.yaml  --input {string_} --output ./detections")

        # %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
        #                      read the pkl files generated by
        #                   retina net stored in detections folder
        # %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
        preds = joblib.load(f"detections/preds.pkl")
        boxes = preds["pred_boxes"]
        scores = preds["scores"]
        cls = preds["pred_classes"]


    # %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
    #                      for pdf files
    # %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
    # with Console().status("processing pdf ... ", spinner="bouncingBall"):
    #
    #     images = convert_from_path("/home/talha/Downloads/Andrew Parr - Hydraulics and Pneumatics_ A Technician's and Engineer's Guide, Second Edition (1999) - libgen.lc.pdf")
    #
    #     Console().print([i.shape for i in images])
    # %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
      # insert somethinmg to database
      # with MongoClient() as client:
      #       logs = client["W9"]["API_LOGS"]

      #       dummy = {
      #             "fpath" : "dummy_path",
      #             "b64_imgs" : ["this", "is", "a", "dummy", "string"],
      #             "scores" : [1.2,561.5, 2.5,6.5,5.5],
      #             "bboxes" : [[1.2, 55, 56, 560], [54, 564, 56, 584]],
      #             "classes" : [1, 52 , 5, 54],
      #             "w9_images" : ["sdgdfsgdf", "dsgdfsgdfgdf0"],
      #             "other_images" : ["dsgfdsgdf", "dsgdsg"],
      #             }
            # logs.insert_one(dummy)
      # %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
      #
      #                 recognize the file extension
      #                 read the file
      #                 save images in separate dirs and make list
      #                 convert them into base64 strings and make list
      #                 loop over images and apply detection
      #                 make a list 'detections' and [1,0,0,1,1,1,0] 0 for not W9 image and 1 for W9 image
      #                 save those images to a separate directory.
      #
      # %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%


      # %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
      #                  do recognition here
      # %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

      # %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
        dummy = {
        "fpath" : f"{fpath}",
        "b64_imgs" : encoded_strings,
        "scores" : scores,
        "bboxes" : boxes,
        "classes" : cls,
        "w9_images" : ["sdgdfsgdf", "dsgdfsgdfgdf0"],
        "other_images" : ["dsgfdsgdf", "dsgdsg"],
        "detections" : [1,0,0,1,1,0],
        }

        return dummy





# @app.get('/recognize', response_model=output_model)
# async def recognition(file_input : input_model):

#       with MongoClient() as client:
#             logs = client["W9"]["API_LOGS"]
#             logs.insert_one(file_input.dict())
#       return {

#       }


if __name__=='__main__':
      # uvicorn.run("API_W9:app", port=8080, limit_concurrency=4, workers=4)

      # uvicorn.run("API_W9:app", port=8080, limit_concurrency=4, reload=True)
      uvicorn.run("API_W9:app", port=8080, reload=True)
